### PR TITLE
Revert "Allow overriding fallback paths for MSBuildExtensionsPath via…

### PR DESCRIPTION
**Pull request by radical**
… a property (#59)"

This reverts commit c4e70a612bbe5454e7ddc6189b9ea8dce01d17c8.

This was not accepted upstream.
Fixes: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/682034

### CODE REVIEW

**Review by mrward — APPROVED** [review]
👍

**Comment by manish** [comment]
@marek-safar can we get this patch backported to `2018-08` too. The linked bug is still affecting VS for Mac when using the `-08` mono branch?

**Comment by radical** [comment]
That commit should be added to xplat-master and then the commit id needs to be bumped in mono's 'packaging/MacSDK/msbuild.py'.

I'm on vacation and don't have access to a laptop right now but @akoepelinger should be able to help.

**Comment by akoeplinger** [comment]
Bumped with https://github.com/mono/mono/commit/f001e691cac66a722196cafe7edb76ea31799f7b, build is available from https://xamjenkinsartifact.azureedge.net/build-package-osx-mono/2018-08/112/f001e691cac66a722196cafe7edb76ea31799f7b/MonoFramework-MDK-5.18.0.144.macos10.xamarin.universal.pkg

**Pull request merged**
