### PR TITLE
Update msbuild from upstream master and fix newly broken tests

### PR DESCRIPTION
**Pull request by radical**

### CODE REVIEW

**Review by akoeplinger — APPROVED** [review]

**Comment by akoeplinger** [comment]
I see there's an upstream `vs15.7` branch now, should we track that one instead?

**Comment by rainersigwald** [comment]
@akoeplinger That's probably a good idea but at the moment we haven't started diverging master from vs15.7. It mostly exists because someone wanted to start up some infrastructure around it.

**Comment by radical** [comment]
Also, this PR targets `xplat-master` so it will continue to track upstream master. And I will track upstream `vs15.6` branch for mono-2017-10 (?).

**Comment by radical** [comment]
Pushed a tiny fix missed earlier. @akoeplinger can we merge this now?

**Comment by akoeplinger** [comment]
@radical I think you can merge on your own or do you not have permissions?

**Comment by radical** [comment]
@akoeplinger I do, but I thought maybe this is the new way! So, should I merge if I have 1 approval?

**Comment by akoeplinger** [comment]
@radical yes one approval is enough :)

**Pull request merged**
