### PR TITLE
Update to the lastest from dotnet/toolset release/3.1xx

### PR DESCRIPTION
**Pull request by lewing**

### CODE REVIEW

**Comment by lewing** [comment]
See https://github.com/dotnet/toolset/pull/3291 for details

**Comment by akoeplinger** [comment]
This seems to be stuck during building msbuild for some reason. I logged into the bot to look at the logs directly but couldn't find out why.

**Comment by radical** [comment]
Add `/m:1` to https://github.com/mono/msbuild/blob/xplat-master/eng/cibuild_bootstrapped_msbuild.sh#L87 and https://github.com/mono/msbuild/blob/xplat-master/eng/cibuild_bootstrapped_msbuild.sh#L119 . This is likely stuck because the second build uses the *just built* msbuild, which will now try to run a parallel build and is getting stuck. Best to debug this locally, but adding `/m:1` will get you a package at least.

**Comment by radical** [comment]
Yikes.. ignore that! I thought I was replying to the "enable parallel build" PR! note to self: don't reply in a hurry!

**Comment by radical** [comment]
I would suggest adding `/v:diag` to get the diag log on the console, that might give us some hints.

**Pull request merged**
