### PR TITLE
Try out parallel builds on OSX

### PR DESCRIPTION
**Pull request by lewing**

### CODE REVIEW

**Comment by kg** [comment]
that CI failure looks hard to troubleshoot. Is there a way for us to get the CI build to record a msbuild binlog so we can see what happened?

**Comment by lewing** [comment]
Probably?
/cc @akoeplinger @radical

**Comment by akoeplinger** [comment]
There's already an upload of the logs in the Jenkins build but I just checked and it's only done after the tests are done, i.e. the one that it uploaded is from a previous build (I fixed that now by adding `git clean` to the job config).

If you can't repro locally we can also just upload the raw .log files.

**Comment by kg** [comment]
Maybe I'm looking in the wrong place, I only see textual logs. An msbuild binary log may be more useful because we're dealing with concurrency issues here, and it's very hard to tell what happened thread-wise from the format of the current .log files. Maybe I'm missing something.

https://github.com/Microsoft/msbuild/blob/master/documentation/wiki/Binary-Log.md

**Comment by marek-safar** [comment]
What is the outcome of this?

**Comment by lewing** [comment]
The attempt caused issues in CI, there appears to still be problems here.  @radical please try this out locally and see if you can reproduce the hang.

**Comment by radical** [comment]
Closing in favor of https://github.com/mono/msbuild/pull/200 .

**Pull request closed without merging**
