### PR TITLE
[xplat-master] Update from upstream

### PR DESCRIPTION
**Pull request by radical**
- And fix up copyright message that broke in an earlier merge

### CODE REVIEW

**Comment by rainersigwald** [comment]
Please don't take this yet; we're not sure yet whether 16.5 will contain ab9b2f36a5ff7a85f842b205d5529e77fdc9d7ab or if that will wait for 16.6.

**Comment by radical** [comment]
@rainersigwald ah, ok. I did notice a branch reverting that! thanks for the heads up

**Comment by radical** [comment]
@rainersigwald though this branch tracks *master*. Could it get reverted even for that?

**Comment by rainersigwald** [comment]
We won't do any force-push shenanigans on `master`; if we wind up needing to back it out super hard we'll do so via an explicit revert commit. So this should be fine--but please be wary on 16.5 tracking for now.

**Comment by radical** [comment]
@monojenkins build Mono OS X Extended

**Review by akoeplinger — APPROVED** [review]

**Pull request merged**
