### PR TITLE
[mono] Add CoherentParent dependencies to stay in sync with `dotnet/toolset`

### PR DESCRIPTION
**Pull request by radical**

### CODE REVIEW

**Comment by radical** [comment]
@mmitche mono/msbuild depends on various SDKs and nuget build tasks, directly. I added maestro subscriptions to update those. But then I realized that I wanted to be sure that we were in sync with what `dotnet/toolset` has. So, I'm adding CoherentParent dependencies to that, here. I just read about it at https://github.com/dotnet/arcade/blob/master/Documentation/Darc.md#coherent-parent-dependencies . Is my understanding correct, and does this look sane?

**Comment by mmitche** [comment]
Yep.  note that you don't need any subscriptions to the individual repos after that. YOu just need a subscription to toolset, and that will update the rest.

**Comment by radical** [comment]
@mmitche Does this mean that the dependency update that we will get, will be the ones that toolset has? IOW, we don't have to worry about what channels toolset subscribes to, per sdk/dependency, instead we just use a single channel for toolset and just get the various sdk bumps that way?

**Comment by mmitche** [comment]
> @mmitche Does this mean that the dependency update that we will get, will be the ones that toolset has? IOW, we don't have to worry about what channels toolset subscribes to, per sdk/dependency, instead we just use a single channel for toolset and just get the various sdk bumps that way?

You will still need to think about input channels and what channel of toolset maps to which branch in your repo, but the rest of dependencies will just go along with what toolset has.

**Review by lewing — APPROVED** [review]

**Pull request merged**
