### PR TITLE
MSBuild 16.10.1

### PR DESCRIPTION
**Pull request by mrward**
- Update to MSBuild 16.10.1 - https://github.com/dotnet/msbuild/commit/2fd48ab730134f7698a14fdd5752349737f0e3bd
- Update to Microsoft.DotNet.MSBuildSdkResolver 5.0.300-servicing.21267.11 to support .NET 6 workloads.

### CODE REVIEW

**Review by Therzok — APPROVED** [review]

**Comment by akoeplinger** [comment]
@mrward looks like there are two test failures in Microsoft.Build.Engine.UnitTests_net472_x86.html from https://xamjenkinsartifact.blob.core.windows.net/test-mono-pull-request-mac-sdk-msbuild/437/msbuild-test-results.zip:

```
✘  Microsoft.Build.UnitTests.BackEnd.BinaryTranslator_Tests.AssemblyNameWithMinimalFields
Shouldly.ShouldAssertException : Shouldly uses your source code to generate its great error messages, build your test project with full debug information to get better error messages\nThe provided expression\n    should be\nAssemblyNameFlags.None\n    but was\r\nAssemblyNameFlags.PublicKey
  at Shouldly.ShouldlyCoreExtensions.AssertAwesomely[T] (T actual, System.Func`2[T,TResult] specifiedConstraint, System.Object originalActual, System.Object originalExpected, System.Func`1[TResult] customMessage, System.String shouldlyMethod) [0x00056] in <cd631af7e9d7403ea1721c3ce03185bf>:0 
  at Shouldly.ShouldBeTestExtensions.ShouldBe[T] (T actual, T expected, System.Func`1[TResult] customMessage) [0x0006d] in <cd631af7e9d7403ea1721c3ce03185bf>:0 
  at Shouldly.ShouldBeTestExtensions.ShouldBe[T] (T actual, T expected) [0x00000] in <cd631af7e9d7403ea1721c3ce03185bf>:0 
  at Microsoft.Build.UnitTests.BackEnd.BinaryTranslator_Tests.HelperAssertAssemblyNameEqual (System.Reflection.AssemblyName expected, System.Reflection.AssemblyName actual) [0x0002e] in <ce3bb5d33e56437b80887c478c112527>:0 
  at Microsoft.Build.UnitTests.BackEnd.BinaryTranslator_Tests.AssemblyNameWithMinimalFields () [0x00020] in <ce3bb5d33e56437b80887c478c112527>:0 
  at (wrapper managed-to-native) System.Reflection.RuntimeMethodInfo.InternalInvoke(System.Reflection.RuntimeMethodInfo,object,object[],System.Exception&)
  at System.Reflection.RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x0006a] in <0adecc3512c7464fbe2c8346f04edd3d>:0 
0.0005796s

✘ Microsoft.Build.UnitTests.BackEnd.BinaryTranslator_Tests.CultureInfo(name: \"sr-Cyrl-CS\")
System.Globalization.CultureNotFoundException : Culture name sr-Cyrl-CS is not supported.\nParameter name: name
  at System.Globalization.CultureInfo..ctor (System.String name, System.Boolean useUserOverride, System.Boolean read_only) [0x00073] in <0adecc3512c7464fbe2c8346f04edd3d>:0 
  at System.Globalization.CultureInfo..ctor (System.String name, System.Boolean useUserOverride) [0x00000] in <0adecc3512c7464fbe2c8346f04edd3d>:0 
  at System.Globalization.CultureInfo..ctor (System.String name) [0x00000] in <0adecc3512c7464fbe2c8346f04edd3d>:0 
  at Microsoft.Build.UnitTests.BackEnd.BinaryTranslator_Tests.CultureInfo (System.String name) [0x00000] in <ce3bb5d33e56437b80887c478c112527>:0 
  at (wrapper managed-to-native) System.Reflection.RuntimeMethodInfo.InternalInvoke(System.Reflection.RuntimeMethodInfo,object,object[],System.Exception&)
  at System.Reflection.RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x0006a] in <0adecc3512c7464fbe2c8346f04edd3d>:0 
```

The second one just looks like a Windows/netcore specific culture issue to me and we can disable it, the first one is probably some Mono bug that's not critical either. I'll push it to this PR.

**Comment by mrward** [comment]
I have seen those two fail locally sometimes. Sometimes they pass and two resource tests fail (which always seemed to fail in the past for me):

```
Failed tests 
0.0304925s 
✘
 Microsoft.Build.UnitTests.GenerateResource_Tests.InProc.PropertyHandling.AttributeForwarding
Shouldly.ShouldAssertException : Shouldly uses your source code to generate its great error messages, build your test project with full debug information to get better error messages\nThe provided expression\n    should be greater than or equal to\n2021-05-24T12:29:21.1712397+01:00\n    but was\n2021-05-24T12:29:21.0000000+01:00\n\nAdditional Info:\n    we're talking here about MyAlternateResource.resources and /var/folders/wp/wg44w5kd3911dm9t8g3fdwgc0000gn/T/tmpcc8897543d5042b39248afefd271df2a.resx
  at Shouldly.ShouldlyCoreExtensions.AssertAwesomely[T] (T actual, System.Func`2[T,TResult] specifiedConstraint, System.Object originalActual, System.Object originalExpected, System.Func`1[TResult] customMessage, System.String shouldlyMethod) [0x00056] in <cd631af7e9d7403ea1721c3ce03185bf>:0 
  at Shouldly.ShouldBeTestExtensions.ShouldBeGreaterThanOrEqualTo[T] (T actual, T expected, System.Func`1[TResult] customMessage) [0x0000d] in <cd631af7e9d7403ea1721c3ce03185bf>:0 
  at Shouldly.ShouldBeTestExtensions.ShouldBeGreaterThanOrEqualTo[T] (T actual, T expected, System.String customMessage) [0x0000d] in <cd631af7e9d7403ea1721c3ce03185bf>:0 
  at Microsoft.Build.UnitTests.GenerateResource_Tests.Utilities.ExecuteTask (Microsoft.Build.Tasks.GenerateResource t) [0x00075] in <23635b9f60c64077ab2b7b77ec2d7e69>:0 
  at Microsoft.Build.UnitTests.GenerateResource_Tests.InProc.PropertyHandling.AttributeForwarding () [0x0008f] in <23635b9f60c64077ab2b7b77ec2d7e69>:0 
  at (wrapper managed-to-native) System.Reflection.RuntimeMethodInfo.InternalInvoke(System.Reflection.RuntimeMethodInfo,object,object[],System.Exception&)
  at System.Reflection.RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x0006a] in <92218043474744ea9d64d27064c35dcb>:0 
Output:
Output file "MyAlternateResource.resources" does not exist.
/Library/Frameworks/Mono.framework/Versions/6.12.0/lib/mono/4.5/resgen.exe /compile /var/folders/wp/wg44w5kd3911dm9t8g3fdwgc0000gn/T/tmpcc8897543d5042b39248afefd271df2a.resx,MyAlternateResource.resources
Processing resource file "/var/folders/wp/wg44w5kd3911dm9t8g3fdwgc0000gn/T/tmpcc8897543d5042b39248afefd271df2a.resx" into "MyAlternateResource.resources".
Processing 1 resources from file "/var/folders/wp/wg44w5kd3911dm9t8g3fdwgc0000gn/T/tmpcc8897543d5042b39248afefd271df2a.resx".
0.111407s 
✘
 Microsoft.Build.UnitTests.GenerateResource_Tests.OutOfProc.PropertyHandling.AttributeForwarding
Shouldly.ShouldAssertException : Shouldly uses your source code to generate its great error messages, build your test project with full debug information to get better error messages\nThe provided expression\n    should be greater than or equal to\n2021-05-24T12:29:24.7041785+01:00\n    but was\n2021-05-24T12:29:24.0000000+01:00\n\nAdditional Info:\n    we're talking here about MyAlternateResource.resources and /var/folders/wp/wg44w5kd3911dm9t8g3fdwgc0000gn/T/tmp474eccc6dcb8499a99a71f4a3feb0f7a.resx
  at Shouldly.ShouldlyCoreExtensions.AssertAwesomely[T] (T actual, System.Func`2[T,TResult] specifiedConstraint, System.Object originalActual, System.Object originalExpected, System.Func`1[TResult] customMessage, System.String shouldlyMethod) [0x00056] in <cd631af7e9d7403ea1721c3ce03185bf>:0 
  at Shouldly.ShouldBeTestExtensions.ShouldBeGreaterThanOrEqualTo[T] (T actual, T expected, System.Func`1[TResult] customMessage) [0x0000d] in <cd631af7e9d7403ea1721c3ce03185bf>:0 
  at Shouldly.ShouldBeTestExtensions.ShouldBeGreaterThanOrEqualTo[T] (T actual, T expected, System.String customMessage) [0x0000d] in <cd631af7e9d7403ea1721c3ce03185bf>:0 
  at Microsoft.Build.UnitTests.GenerateResource_Tests.Utilities.ExecuteTask (Microsoft.Build.Tasks.GenerateResource t) [0x00075] in <23635b9f60c64077ab2b7b77ec2d7e69>:0 
  at Microsoft.Build.UnitTests.GenerateResource_Tests.OutOfProc.PropertyHandling.AttributeForwarding () [0x00083] in <23635b9f60c64077ab2b7b77ec2d7e69>:0 
  at (wrapper managed-to-native) System.Reflection.RuntimeMethodInfo.InternalInvoke(System.Reflection.RuntimeMethodInfo,object,object[],System.Exception&)
  at System.Reflection.RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x0006a] in <92218043474744ea9d64d27064c35dcb>:0 
Output:
Input file "/var/folders/wp/wg44w5kd3911dm9t8g3fdwgc0000gn/T/tmp474eccc6dcb8499a99a71f4a3feb0f7a.resx" is newer than output file "MyAlternateResource.resources".
/Library/Frameworks/Mono.framework/Versions/6.12.0/lib/mono/4.5/resgen.exe /compile /var/folders/wp/wg44w5kd3911dm9t8g3fdwgc0000gn/T/tmp474eccc6dcb8499a99a71f4a3feb0f7a.resx,MyAlternateResource.resources 
Read in 1 resources from '/var/folders/wp/wg44w5kd3911dm9t8g3fdwgc0000gn/T/tmp474eccc6dcb8499a99a71f4a3feb0f7a.resx'
Writing resource file...  Done.

```

**Comment by akoeplinger** [comment]
Ah interesting. Are you still using HFS+ as the disk format by chance? Looks like it's only recording the timestamp with second precision.

**Comment by mrward** [comment]
Yeah running the tests on a `Mac OS Extended` drive.

**Review by akoeplinger — APPROVED** [review]

**Pull request merged**
