### PR TITLE
Update bundled SDKs to match VS 15.4

### PR DESCRIPTION
**Pull request by radical**

### CODE REVIEW

**Review by akoeplinger — APPROVED** [review]
All the files changed permission from 644 → 755 but other than that looks good to me.

**Review by marek-safar — CHANGES_REQUESTED** [review]
Please use corresponding mono branches instead of d15.4, e.g. `mono-2017-06`
Could you also revert the permission changes

**Comment by radical** [comment]
Fixed file permissions. The branch being used (`d15.4`) here is only for msbuild to track VS 15.4 . The relevant mono branch would get a separate PR to point to a specific hash, so that branch will be `2017-06`.

**Comment by marek-safar** [comment]
Mono is detached from d15 so d15.4 makes no sense

**Comment by radical** [comment]
Opened https://github.com/mono/msbuild/pull/25 instead, which merges to `mono-2017-06` branch.

**Pull request closed without merging**
