### PR TITLE
Complete upstream the merge

### PR DESCRIPTION
**Pull request by radical**
- Fixes the build after the previous upstream merge
- Moves the build from net461 to net471
- Updates the bundled SDKs

### CODE REVIEW

**Comment by radical** [comment]
@marek-safar This is the change for the denied assembly task - https://github.com/mono/msbuild/pull/71/commits/393268fe29c3f0b53911d82c13bd33b06e9023c5

**Comment by radical** [comment]
@marek-safar @akoeplinger  These assemblies are being deployed with msbuild now, because of https://github.com/dotnet/sdk/blob/master/src/Tasks/Microsoft.NET.Build.Extensions.Tasks/msbuildExtensions/Microsoft/Microsoft.NET.Build.Extensions/Microsoft.NET.Build.Extensions.NETFramework.targets#L70-L78

Does this apply to us?

```
lib/mono/msbuild/15.0/bin/System.Data.Common.dll
lib/mono/msbuild/15.0/bin/System.Diagnostics.StackTrace.dll
lib/mono/msbuild/15.0/bin/System.Diagnostics.Tracing.dll
lib/mono/msbuild/15.0/bin/System.Globalization.Extensions.dll
lib/mono/msbuild/15.0/bin/System.Net.Http.dll
lib/mono/msbuild/15.0/bin/System.Net.Sockets.dll
lib/mono/msbuild/15.0/bin/System.Runtime.Serialization.Primitives.dll
lib/mono/msbuild/15.0/bin/System.Security.Cryptography.Algorithms.dll
lib/mono/msbuild/15.0/bin/System.Security.SecureString.dll
lib/mono/msbuild/15.0/bin/System.Threading.Overlapped.dll
lib/mono/msbuild/15.0/bin/System.Xml.XPath.XDocument.dll
```

**Comment by marek-safar** [comment]
I think we should filter them out, they look like Facades or implementation copies

**Comment by akoeplinger** [comment]
Once we have .NET 4.7.2 support (https://github.com/mono/mono/issues/8657) we could just target that which will avoid those assemblies being copied by the SDK.

**Comment by borgdylan** [comment]
When will this be merged?

**Comment by borgdylan** [comment]
@radical ping

**Comment by radical** [comment]
@borgdylan I need to add one more fix to this, will merge after that.

**Comment by borgdylan** [comment]
Thanks for clarifying. I will woll pull and attempt to rebuild once you are done. I am currently stuck on an older build as the current code does not build. I have identified that this PR fixes at least one of the issues I encountered. Keep up the good work and thanks!

**Review by akoeplinger — APPROVED** [review]

**Pull request merged**
