### PR TITLE
[mono] Merge mono-2019-06 and upstream master

### PR DESCRIPTION
**Pull request by radical**
- merge mono-2019-06
- upstream master, HEAD: e2f3fed

### CODE REVIEW

**Comment by rainersigwald** [comment]
Intention check: upstream master has moved to 16.4. Are you ready to move xplat-master to follow? Or should it track upstream `vs16.3` for now?

**Comment by radical** [comment]
@lewing @akoeplinger thoughts on what @rainersigwald said?

**Comment by lewing** [comment]
Hmmm, that is a good point.  I think the plan right now is that x.4 will still use 2019-06 but so will x.3 service releases so we are going to have to decide how to handle that.

**Comment by lewing** [comment]
We should keep 2019-06 targeting x.3.  xplat-master (mono 2019-08 and master) should target x.4

**Review by lewing — APPROVED** [review]

**Comment by radical** [comment]
Updated to latest master, again, since it has been some time since this PR was created.

**Pull request merged**
