### PR TITLE
Update with latest from MSBuild xplat branch

### PR DESCRIPTION
**Pull request by DustinCampbell**
The merge was largely mechanical. However, `ToolsetConfigurationReaderHelpers.ConfigurationFileMayHaveToolsets(...)`, which is used in the code to retrieve the TargetFrameworkRootPathSearchPaths property from the configuration file was removed. I've added a private copy of this method into FrameworkLocationHelper.cs for now.

### CODE REVIEW

**Comment by radical** [comment]
Thanks for the PR! I got around to it very late. I have now updated the branch to track vs15-rtw branch upstream. Closing this!

**Comment by DustinCampbell** [comment]
Sounds great -- thanks!

**Comment by DustinCampbell** [comment]
I assume that's xplat-master?

**Comment by rainersigwald** [comment]
@DustinCampbell `vs15-rtw` is our release branch for v15, it was forked from `xplat` not too long ago.

**Comment by radical** [comment]
@DustinCampbell both `xplat-c9` and `xplat-master` have the changes. `xplat-c9` is for the upcoming release and will track whatever VS2017 will have, so, `vs15-rtw` from upstream. And `xplat-master` will be for future releases, so will track xplat. Though, currently, they are almost the same.

**Comment by DustinCampbell** [comment]
Does it need anything for extra for Mono (e.g. targets and such)? If not -- AWESOME!

**Comment by radical** [comment]
There are still some (few!) things specific to Mono, that are not upstream yet. The important ones are already in PR form, being discussed and probably pending on my side, for updates!

**Comment by DustinCampbell** [comment]
OK. So, _eventually_. :smile:

Anyway, that's great news. I'll continue to build from xplat-c9 for OmniSharp for now.

**Pull request closed without merging**
