### PR TITLE
Add support for building on and targeting Mono

### PR DESCRIPTION
**Pull request by radical**
We used old netcore 1.x for building msbuild. We wanted to move to newer netcore 2.x for many reasons like being able to use `PackageReference`, switch to newer SDK projects and being able to build on High Sierra. Upstream master moved switched over to that for netcore and full framework builds. This PR adds support for using that new system to build for mono.

Steps to build are still the same:
```
build: make all-mono
test: make test-mono
clean: make clean

install: ./install-mono-prefix.sh <mono_prefix>
```

Also, we now try to watch for any changes in the build directory like new assemblies or files showing up or getting removed due to (for example) changes upstream. This way we always "approve" any such changes for our fork.
`mono/README.md` has a little more info on this.

### CODE REVIEW

**Comment by radical** [comment]
Not ready for review yet. Pending:

- Test with a real .pkg from the CI
- 2 failing tests - probably need to file an upstream issue for these

**Comment by radical** [comment]
For anyone trying out this branch:

build: `make all-mono`
test: `make test-mono`
clean: `make clean`

install: `./install-mono-prefix.sh <mono_prefix>`

**Comment by marek-safar** [comment]
@radical could you fill the description with more details and reasoning for this change

**Comment by radical** [comment]
Updated the description.

**Comment by directhex** [comment]
It mooooooooostly achieves the objective. Builds if I uninstall cmake, on Ubuntu 18.04. https://github.com/AArnott/Nerdbank.GitVersioning/issues/143

**Comment by radical** [comment]
Added support for using a bootstrap msbuild.

**Comment by radical** [comment]
@directhex maybe I can try to work around that. I tried just disabling the package reference, but that didn't work. Can you share the binary logs (`artifacts/Release-MONO/log/Build*.binlog`)? I want to see the trace and where in the build it was invoked.

**Comment by radical** [comment]
hm maybe not.

**Comment by radical** [comment]
After lots of rounds trying build-pkg+fix, I finally have a package that works from https://github.com/mono/mono/pull/8388 . So, this PR is also ready for review+merge now.

There are other things to come right after this:
- another upstream merge
- SDK+resolver updates
- 2018-02 port+updates

**Review by marek-safar — APPROVED** [review]

**Pull request merged**
