### PR TITLE
[mono] Linux build fixes

### PR DESCRIPTION
**Pull request by radical**

### CODE REVIEW

**Comment by radical** [comment]
@directhex What should be done about `libhostfxr.so`? I added it to the `extract_and_copy_hostfxr.sh` scriptbut that particular .so didn't work on my ubuntu 16.04, maybe it works on others. Maybe for packaging you want to pick it manually? For other people building it for local installation, maybe this should be controllable via a msbuild property - whether to copy the libhostfxr.so or not - defaulting to .. no-copy?

**Comment by radical** [comment]
One more error is left after this, which is the `License` file issue with arcade. I will do a followup for that.

**Comment by borgdylan** [comment]
I'd suggest emitting a message on the command to remind people building by hand to copy the hostfxr and where it's most likely to reside.

**Comment by borgdylan** [comment]
For install.proj: I'd recommend ```ln -sf``` for all links. Attempting to use ```-n``` will break if a prior links already exists. Using ```-f``` ensures the installation process carries on if the link already exists.

**Comment by directhex** [comment]
Bundling a libhostfxr.so is basically bad and wrong - it doesn't account for distributions or architectures. In our packages, we build our own (it comes from dotnet/core-setup.git), and use a complicated system of levers and pulleys to pull in the package containing libhostfxr when installing msbuild

**Comment by borgdylan** [comment]
@directhex When installing msbuild I copy the hostfxr from the installation directly of the newest .NET Core I have installed. Is that the right way of doing it when installing manually? Is there a published script that you would recommend instead?

**Comment by directhex** [comment]
@borgdylan that's one way to do it. It's a problem for us, since we ship on multiple architectures. https://github.com/mono/linux-packaging-core-setup/blob/master/debian/rules is how the packaging works.

**Comment by treeowl** [comment]
What's holding this up?

**Pull request merged**
